### PR TITLE
Update 1736.md

### PR DESCRIPTION
**Pull request by gerth2**
Added some basic info for code releases

### CODE REVIEW

**Comment by virtuald** [comment]
Thanks!

**Comment by gerth2** [comment]
No problem, glad to be able to help a bit!

**Comment by virtuald** [comment]
If you wanted to help a bit more, you could put a little blurb about your team on the page! :)

**Comment by dkt01** [comment]
@gerth2 It looks like 1736.md is failing in all the Travis builds after this point. [Build Details](https://travis-ci.org/firstwiki/frc1000/builds/174009222)
@virtuald Is Travis configured to report failure on errors?  See line 255 of build 34 output.

**Comment by virtuald** [comment]
Ha. Well crap.

**Comment by gerth2** [comment]
I noticed it didn't seem like our page was working, but didn't bother to look into it much. A quick diff with another team's page doesn't reveal anything much meaningful.... I'm guessing that travis error is due to the 1736 md file not following an expected convention?
Looks like I might have an extra newline in there....

**Comment by gerth2** [comment]
Blindly flailing in https://github.com/firstwiki/frc1000/pull/13

**Comment by virtuald** [comment]
@dkt01 it looks like jekyll no longer returns a non-zero return code for certain types of errors. I'm tracking this at https://github.com/firstwiki/wiki/issues/59

**Pull request merged**
