### PR TITLE
Adding Janksters 1967 to the fold.

### PR DESCRIPTION
**Pull request by bobwolff68**
Have only created a couple pull requests ... ever ... let me know I did this right? :)

### CODE REVIEW

**Comment by virtuald** [comment]
Yep, thanks for the PR!

**Comment by devyntk** [comment]
Because of some bad syntax, you're not showing up. Give a minute and I'll fix it for you.

**Comment by virtuald** [comment]
Hm. We should add a linter or something to catch these...

**Comment by devyntk** [comment]
Fixed it in #11 You just needed to close your parameters at the top with another `---`

**Comment by bobwolff68** [comment]
Thanks! When should I see the directory update @ https://firstwiki.github.io/wiki/robot-code-directory for the team?

**Comment by devyntk** [comment]
Usually it takes a few seconds. It's take at most 30 seconds for me to load it once. It looks like it's already updated and there for you!

**Comment by bobwolff68** [comment]
Very odd - doesn't show up on Chrome after doing a refresh, but I opened up a firefox window and put the link in there and it's showing live. Some caching issue on the wiki?

**Comment by bobwolff68** [comment]
Hmm - and just now it does show up after many more refreshes on Chrome...  Anyway - thanks for your help!

**Pull request merged**
